#!/bin/sh

class=$(playerctl metadata --player=cider --format '{{lc(status)}}')
icon=" "

if [[ $class == "playing" ]]; then
  info=$(playerctl metadata --player=cider --format '{{artist}} - {{title}}')
  if [[ ${#info} > 40 ]]; then
    info=$(echo $info | cut -c1-40)"..."
  fi
  text=$icon"\u00A0"$info
elif [[ $class == "paused" ]]; then
  text=$icon
elif [[ $class == "stopped" ]]; then
  text=""
fi

echo -e "{\"text\":\""$text"\", \"class\":\""$class"\"}"
